### ISSUE TITLE
Rename "ym3438_t->slot" field into anything to avoid possible conflicts with Qt applications

### ISSUE THREAD

**Issue by Wohlstand** [nukeykt/Nuked-OPN2#1]
Because Qt declares a dummy "slot" macro, all "slot" variables are becoming as nothing (and compiler fails to build this code). I got this trouble in the OPL3 Bank Editor while I worked on embedding of Nuked OPL3 emulator.

When I'll return to home, I'll post the pull request where I will rename that by myself (by using of embedded Qt Creator's refactoring features).

**Comment by loki666** [comment]
Just build this file out of Qt

**Comment by Wohlstand** [comment]
Sorry for a delay, I just now [sent a pull-request](https://github.com/nukeykt/Nuked-OPN2/pull/2) which fixes this issue.

> Just build this file out of Qt
...and produce extra proxy workaround for this 😛. Unlike a buggy proprietary Chinese binary SDKs for various surveillance cameras at my job, it's a free and open-source project where everyone is able to make the true fix rather implementing extra proxies over current stuff without modifying of it.
