### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by Franticware** [nukeykt/Nuked-OPN2#16]
Hi, I noticed a discrepancy between the current version and an older one used here https://github.com/Wohlstand/OPN2BankEditor/tree/master/src/opl/chips/nuked
It states LGPL v2.1, whereas this latest one is GPL v2.0. Is it possible to use 1.0.10 as LGPL v2.1 too?
Not to mention another weird non-standard license claimed here: https://github.com/nukeykt/Genesis-Plus-GX/blob/master/core/sound/ym3438.c
None of these is ideal, BSD/MIT/Zlib would be perfect from a technical standpoint (e.g. not having to dynamically link, usability for embedded stuff).
Please clarify the current status, otherwise I will have to use 1.0.9 which is LGPL'ed.
Thank you.

**Comment by Wohlstand** [comment]
The thing at me is the same code as here, with an exception it has been slightly extended to support the soft-panning feature. I guess, this one here is also LGPL-licensed, but @nukeykt hadn't clarify this here

**Comment by nukeykt** [comment]
Feel free to use it under LGPL

**Comment by Franticware** [comment]
Thank you.
