### ISSUE TITLE
Reading per-channel output values from chip

### ISSUE THREAD

**Issue by itsmevjnk** [nukeykt/Nuked-OPN2#30]
Hi, I'm planning to use this emulator in my project (VGM parser/player), where I've designed that each emulator must provide an array of output values for each channel instead of a single mixed value. So far this is working with okaxaki's emulators such as emu2149 or emu76489, but I'm wondering if this is also possible with Nuked-OPN2. And yes, I'm aware that the OPN2 chip uses a different mixing method, which I'm thinking that I can write an override of the mixing function in my code to accommodate this.

**Comment by nukeykt** [comment]
YM3438 doesn't have mixer and just outputs individual channel values sequentally (in this order every 4 cycles IIRC: 2, 6, 4, 1, 5, 3), so you can do something like this
```
ym3438_t fm;
int mem[24][2];
int cycle = fm.cycles; // synchronize with internal counter

OPN2_Clock(&fm, buffer)

mem[cycle][0] = buffer[0];
mem[cycle][1] = buffer[1];
```
and then do this to get individual value:
```
int ch2_left_value = mem[0][0] + mem[1][0] + mem[2][0] + mem[3][0];
int ch2_right_value = mem[0][1] + mem[1][1] + mem[2][1] + mem[3][1];
int ch6_left_value = mem[4][0] + mem[5][0] + mem[6][0] + mem[7][0];
...
etc

```

**Comment by itsmevjnk** [comment]
Thanks for the response. In any case I ended up checking out @Wohlstand's extensions (`OPN2_Generate` function to be more specific - can be seen [here](https://github.com/Wohlstand/libOPNMIDI/blob/23d817cb28bbb615d9d32eefa83902dcedfae825/src/chips/nuked/ym3438.c#L1508)) and adapted the channel output data updating code into mine - I think that should be the same as what you suggested.

Here's that implementation in my project for future reference by anyone stumbling upon this: https://github.com/itsmevjnk/yavgmp/blob/9227e87291827f6d7ae5e41c16ffc33fcad32cce/vgmchips/opn2/opn2_wrapper.cpp#L30
