### ISSUE TITLE
G# of any octave gives weird playback when FM modulation is more than 1

### ISSUE THREAD

**Issue by Wohlstand** [nukeykt/Nuked-OPN2#6]
While I experimenting with a bank editor to implement switchable emulators, I found a weird thing with playback. 
Reproduce of this is shown on this video: https://youtu.be/a48FXMY1ZNM
Is it's a bug of emulator or it's a normal behavior of real chip?

A bit later I'll post my stuff into OPN2 Bank Editor repo where everything will be.

**Comment by nukeykt** [comment]
Can you write exact F-number and block values here?

**Comment by Wohlstand** [comment]
Wait a sec, I'll put the dumper to capture entire stuff passing to the chip...

**Comment by Wohlstand** [comment]
```
"0: 0x28 => 0x00"
"0: 0x40 => 0x1d"
"0: 0x44 => 0x1c"
"0: 0x48 => 0x7f"
"0: 0x4c => 0x7f"
"0: 0x28 => 0x01"
"0: 0x41 => 0x1d"
"0: 0x45 => 0x1c"
"0: 0x49 => 0x7f"
"0: 0x4d => 0x7f"
"0: 0x28 => 0x02"
"0: 0x42 => 0x1d"
"0: 0x46 => 0x1c"
"0: 0x4a => 0x7f"
"0: 0x4e => 0x7f"
"0: 0x28 => 0x04"
"1: 0x40 => 0x1d"
"1: 0x44 => 0x1c"
"1: 0x48 => 0x7f"
"1: 0x4c => 0x7f"
"0: 0x28 => 0x05"
"1: 0x41 => 0x1d"
"1: 0x45 => 0x1c"
"1: 0x49 => 0x7f"
"1: 0x4d => 0x7f"
"0: 0x28 => 0x06"
"1: 0x42 => 0x1d"
"1: 0x46 => 0x1c"
"1: 0x4a => 0x7f"
"1: 0x4e => 0x7f"
```

**Comment by nukeykt** [comment]
Ok. Thanks!

**Comment by Wohlstand** [comment]
Okay, that crap has finally gone! :+1: 
Only left it on highest octaves where `block` has it's maximal value and F-Number is using to reach the maximum possible "height", which would be kept as-is.
